---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    name: dummy-device-plugin
  name: dummy-device-plugin
spec:
  selector:
    matchLabels:
      name: dummy-device-plugin
  template:
    metadata:
      labels:
        name: dummy-device-plugin
    spec:
      hostNetwork: true
      containers:
      - name: dummy-device-plugin
        image: quay.io/ebelarte/oc-dummy-device-plugin:0.1
        #args: ["-log-level", "debug"]
        securityContext:
          privileged: true
        volumeMounts:
          - name: device-plugin
            mountPath: /var/lib/kubelet/device-plugins
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
